#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/lge/sm8250-common

PRODUCT_COPY_FILES += \
    vendor/lge/sm8250-common/proprietary/product/etc/permissions/telephony_product_privapp-permissions-qti.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/telephony_product_privapp-permissions-qti.xml \
    vendor/lge/sm8250-common/proprietary/system_ext/etc/dpm/dpm.conf:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/dpm/dpm.conf \
    vendor/lge/sm8250-common/proprietary/system_ext/etc/init/wfdservice.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/wfdservice.rc \
    vendor/lge/sm8250-common/proprietary/system_ext/etc/permissions/audiosphere.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/audiosphere.xml \
    vendor/lge/sm8250-common/proprietary/system_ext/etc/permissions/com.android.hotwordenrollment.common.util.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.hotwordenrollment.common.util.xml \
    vendor/lge/sm8250-common/proprietary/system_ext/etc/permissions/com.qti.dpmframework.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qti.dpmframework.xml \
    vendor/lge/sm8250-common/proprietary/system_ext/etc/permissions/dpmapi.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/dpmapi.xml \
    vendor/lge/sm8250-common/proprietary/system_ext/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qcrilhook.xml \
    vendor/lge/sm8250-common/proprietary/system_ext/etc/permissions/qti_libpermissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_libpermissions.xml \
    vendor/lge/sm8250-common/proprietary/system_ext/etc/permissions/qti_permissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_permissions.xml \
    vendor/lge/sm8250-common/proprietary/system_ext/etc/permissions/telephony_system-ext_privapp-permissions-qti.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/telephony_system-ext_privapp-permissions-qti.xml \
    vendor/lge/sm8250-common/proprietary/system_ext/etc/permissions/wfd-system-ext-privapp-permissions-qti.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/wfd-system-ext-privapp-permissions-qti.xml \
    vendor/lge/sm8250-common/proprietary/system_ext/etc/seccomp_policy/wfdservice.policy:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/seccomp_policy/wfdservice.policy \
    vendor/lge/sm8250-common/proprietary/system_ext/etc/wfdconfigsink.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/wfdconfigsink.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cacert_location.pem:$(TARGET_COPY_OUT_VENDOR)/etc/cacert_location.pem \
    vendor/lge/sm8250-common/proprietary/vendor/etc/charger_fstab.qti:$(TARGET_COPY_OUT_VENDOR)/etc/charger_fstab.qti \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/mwqem.conf:$(TARGET_COPY_OUT_VENDOR)/etc/cne/mwqem.conf \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/profileMwqem.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/profileMwqem.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile1.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile2.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile3.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile4.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile5.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile6.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile1.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile15.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile15.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile16.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile16.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile17.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile18.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile19.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile19.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile2.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile20.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile21.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile21.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile3.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile32.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile32.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile4.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile5.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile6.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile7.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile7.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile1.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile2.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile3.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile4.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile5.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile6.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/configstore/vpp.configstore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/configstore/vpp.configstore.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/netmgr_config.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/default-permissions/com.qualcomm.qti.cne.xml:$(TARGET_COPY_OUT_VENDOR)/etc/default-permissions/com.qualcomm.qti.cne.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/excluded-input-devices.xml:$(TARGET_COPY_OUT_VENDOR)/etc/excluded-input-devices.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/gpfspath_oem_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gpfspath_oem_config.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-qti.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/android.hardware.drm@1.1-service.wfdhdcp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.1-service.wfdhdcp.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/android.hardware.drm@1.3-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.3-service.widevine.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/android.hardware.gnss@2.1-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss@2.1-service-qti.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/android.hardware.keymaster@4.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.0-service-qti.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/android.hardware.neuralnetworks@1.3-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks@1.3-service-qti.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/cnd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/cnd.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/com.qualcomm.qti.wifidisplayhal@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/com.qualcomm.qti.wifidisplayhal@1.0-service.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/dataadpl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataadpl.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/dataqti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataqti.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/dpmQmiMgr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dpmQmiMgr.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/ims_rtp_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ims_rtp_daemon.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/imsdatadaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsdatadaemon.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/imsqmidaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsqmidaemon.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/imsrcsd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsrcsd.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/init.time_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.time_daemon.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/netmgrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netmgrd.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/qcrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qcrild.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/qdcmss.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qdcmss.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/qmipriod.debug.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qmipriod.debug.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/qmipriod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qmipriod.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/qseecomd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qseecomd.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/shsusrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/shsusrd.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/ssgtzd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ssgtzd.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/vendor.display.color@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.display.color@1.0-service.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/vendor.lge.hardware.lgdata@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.lge.hardware.lgdata@1.1-service.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/vendor.lge.hardware.powerhint.rescontrol@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.lge.hardware.powerhint.rescontrol@2.0-service.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/vendor.lge.hardware.vss_ims@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.lge.hardware.vss_ims@1.0-service.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/vendor.qti.adsprpc-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.adsprpc-service.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/vendor.qti.cdsprpc-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.cdsprpc-service.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/vendor.qti.esepowermanager@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.esepowermanager@1.1-service.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/vendor.qti.hardware.alarm@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.alarm@1.0-service.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/vendor.qti.hardware.charger_monitor@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.charger_monitor@1.0-service.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/vendor.qti.hardware.dsp@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.dsp@1.0-service.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/vendor.qti.hardware.factory@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.factory@1.0-service.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/vendor.qti.hardware.qteeconnector@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qteeconnector@1.0-service.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/vendor.qti.hardware.sensorscalibrate@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.sensorscalibrate@1.0-service.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/vendor.qti.hardware.soter@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.soter@1.0-service.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/vendor.qti.media.c2@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.media.c2@1.0-service.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/vendor.qti.power.pasrmanager@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.power.pasrmanager@1.0-service.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/vendor.qti.qspmhal@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.qspmhal@1.0-service.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/vendor.qti.rmt_storage.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.rmt_storage.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/vendor.qti.tftp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.tftp.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/vendor.sensors.qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sensors.qti.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/vendor.sensors.sscrpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sensors.sscrpcd.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/vppservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vppservice.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/init/wfdvndservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wfdvndservice.rc \
    vendor/lge/sm8250-common/proprietary/vendor/etc/msm_irqbalance.conf:$(TARGET_COPY_OUT_VENDOR)/etc/msm_irqbalance.conf \
    vendor/lge/sm8250-common/proprietary/vendor/etc/permissions/vendor-qti-hardware-sensorscalibrate.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/vendor-qti-hardware-sensorscalibrate.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/permissions/vendor.qti.hardware.factory.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/vendor.qti.hardware.factory.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/sec_config:$(TARGET_COPY_OUT_VENDOR)/etc/sec_config \
    vendor/lge/sm8250-common/proprietary/vendor/etc/seccomp_policy/atfwd@2.0.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/atfwd@2.0.policy \
    vendor/lge/sm8250-common/proprietary/vendor/etc/seccomp_policy/codec2.vendor.base-arm.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/codec2.vendor.base-arm.policy \
    vendor/lge/sm8250-common/proprietary/vendor/etc/seccomp_policy/codec2.vendor.ext-arm.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/codec2.vendor.ext-arm.policy \
    vendor/lge/sm8250-common/proprietary/vendor/etc/seccomp_policy/gnss@2.0-base.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-base.policy \
    vendor/lge/sm8250-common/proprietary/vendor/etc/seccomp_policy/gnss@2.0-xtra-daemon.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-xtra-daemon.policy \
    vendor/lge/sm8250-common/proprietary/vendor/etc/seccomp_policy/gnss@2.0-xtwifi-client.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-xtwifi-client.policy \
    vendor/lge/sm8250-common/proprietary/vendor/etc/seccomp_policy/gnss@2.0-xtwifi-inet-agent.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/gnss@2.0-xtwifi-inet-agent.policy \
    vendor/lge/sm8250-common/proprietary/vendor/etc/seccomp_policy/imsrtp.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/imsrtp.policy \
    vendor/lge/sm8250-common/proprietary/vendor/etc/seccomp_policy/mediacodec.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediacodec.policy \
    vendor/lge/sm8250-common/proprietary/vendor/etc/seccomp_policy/qspm.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qspm.policy \
    vendor/lge/sm8250-common/proprietary/vendor/etc/seccomp_policy/qti-systemd.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qti-systemd.policy \
    vendor/lge/sm8250-common/proprietary/vendor/etc/seccomp_policy/vendor.qti.hardware.dsp.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/vendor.qti.hardware.dsp.policy \
    vendor/lge/sm8250-common/proprietary/vendor/etc/seccomp_policy/wfdhdcphalservice.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/wfdhdcphalservice.policy \
    vendor/lge/sm8250-common/proprietary/vendor/etc/seccomp_policy/wfdvndservice.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/wfdvndservice.policy \
    vendor/lge/sm8250-common/proprietary/vendor/etc/seccomp_policy/wifidisplayhalservice.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/wifidisplayhalservice.policy \
    vendor/lge/sm8250-common/proprietary/vendor/etc/ssg/ta_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/ssg/ta_config.json \
    vendor/lge/sm8250-common/proprietary/vendor/etc/ssg/tz_whitelist.json:$(TARGET_COPY_OUT_VENDOR)/etc/ssg/tz_whitelist.json \
    vendor/lge/sm8250-common/proprietary/vendor/etc/system_properties.xml:$(TARGET_COPY_OUT_VENDOR)/etc/system_properties.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/thermal-engine-8250.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-8250.conf \
    vendor/lge/sm8250-common/proprietary/vendor/etc/thermal-engine-default.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-default.conf \
    vendor/lge/sm8250-common/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/lge/sm8250-common/proprietary/vendor/etc/wfdconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/wfdconfig.xml \
    vendor/lge/sm8250-common/proprietary/vendor/etc/xtra_root_cert.pem:$(TARGET_COPY_OUT_VENDOR)/etc/xtra_root_cert.pem \
    vendor/lge/sm8250-common/proprietary/vendor/firmware/a650_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a650_gmu.bin \
    vendor/lge/sm8250-common/proprietary/vendor/firmware/a650_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a650_sqe.fw \
    vendor/lge/sm8250-common/proprietary/vendor/firmware/a650_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a650_zap.b00 \
    vendor/lge/sm8250-common/proprietary/vendor/firmware/a650_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a650_zap.b01 \
    vendor/lge/sm8250-common/proprietary/vendor/firmware/a650_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a650_zap.b02 \
    vendor/lge/sm8250-common/proprietary/vendor/firmware/a650_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a650_zap.elf \
    vendor/lge/sm8250-common/proprietary/vendor/firmware/a650_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a650_zap.mdt \
    vendor/lge/sm8250-common/proprietary/vendor/firmware/htbtfw20.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/htbtfw20.tlv \
    vendor/lge/sm8250-common/proprietary/vendor/firmware/htnv20.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/htnv20.bin \
    vendor/lge/sm8250-common/proprietary/vendor/firmware/libpn557_fw.so:$(TARGET_COPY_OUT_VENDOR)/firmware/libpn557_fw.so \
    vendor/lge/sm8250-common/proprietary/vendor/firmware/libpn557_fw_64.so:$(TARGET_COPY_OUT_VENDOR)/firmware/libpn557_fw_64.so \
    vendor/lge/sm8250-common/proprietary/vendor/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xx.cnt \
    vendor/lge/sm8250-common/proprietary/vendor/firmware/tfa98xx_reva.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xx_reva.cnt \
    vendor/lge/sm8250-common/proprietary/vendor/radio/qcril_database/qcril.db:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/qcril.db \
    vendor/lge/sm8250-common/proprietary/vendor/radio/qcril_database/upgrade/0_initial.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/0_initial.sql \
    vendor/lge/sm8250-common/proprietary/vendor/radio/qcril_database/upgrade/1_version_intro.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/1_version_intro.sql \
    vendor/lge/sm8250-common/proprietary/vendor/radio/qcril_database/upgrade/2_version_add_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/2_version_add_wps_config.sql \
    vendor/lge/sm8250-common/proprietary/vendor/radio/qcril_database/upgrade/3_version_update_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/3_version_update_wps_config.sql \
    vendor/lge/sm8250-common/proprietary/vendor/radio/qcril_database/upgrade/4_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/4_version_update_ecc_table.sql \
    vendor/lge/sm8250-common/proprietary/vendor/radio/qcril_database/upgrade/5_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/5_version_update_ecc_table.sql \
    vendor/lge/sm8250-common/proprietary/vendor/radio/qcril_database/upgrade/6_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/6_version_update_ecc_table.sql \
    vendor/lge/sm8250-common/proprietary/vendor/radio/qcril_database/upgrade/7_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/7_version_update_ecc_table.sql \
    vendor/lge/sm8250-common/proprietary/vendor/radio/qcril_database/upgrade/8_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/8_version_update_ecc_table.sql

PRODUCT_PACKAGES += \
    LGDataFeature_vendor \
    btaudio_offload_if \
    com.qualcomm.qti.imscmservice@1.0 \
    com.qualcomm.qti.imscmservice@2.0 \
    com.qualcomm.qti.imscmservice@2.1 \
    com.qualcomm.qti.imscmservice@2.2 \
    com.qualcomm.qti.uceservice@2.0 \
    com.qualcomm.qti.uceservice@2.1 \
    com.qualcomm.qti.uceservice@2.2 \
    com.qualcomm.qti.uceservice@2.3 \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libq3dtools_adreno \
    libq3dtools_esx \
    android.hardware.bluetooth@1.0-impl-qti \
    com.dsi.ant@1.0-impl \
    sound_trigger.primary.kona \
    vendor.lge.hardware.vss_ims@1.0-impl \
    vendor.qti.hardware.alarm@1.0-impl \
    vendor.qti.hardware.bluetooth_audio@2.0-impl \
    vendor.qti.hardware.bluetooth_audio@2.1-impl \
    vendor.qti.hardware.bluetooth_sar@1.1-impl \
    vendor.qti.hardware.btconfigstore@1.0-impl \
    vendor.qti.hardware.btconfigstore@2.0-impl \
    vendor.qti.hardware.capabilityconfigstore@1.0-impl \
    vendor.qti.hardware.fm@1.0-impl \
    vendor.qti.hardware.qseecom@1.0-impl \
    vendor.qti.hardware.qteeconnector@1.0-impl \
    vendor.qti.hardware.sensorscalibrate@1.0-impl \
    vendor.qti.power.pasrmanager@1.0-impl \
    vulkan.adreno \
    lgdatavendorlib \
    lge_qcci_data \
    lib-imscmservice \
    lib-imsdpl \
    lib-imsqimf \
    lib-imsrcs-v2 \
    lib-imsrcsbaseimpl \
    lib-imsvtcore \
    lib-imsxml \
    lib-rcsconfig \
    lib-rtpcommon \
    lib-rtpcore \
    lib-rtpsl \
    lib-siputility \
    lib-uceservice \
    libC2D2 \
    libCB \
    libDxHdcp \
    libGPQTEEC_vendor \
    libGPTEE_vendor \
    libGPreqcancel \
    libGPreqcancel_svc \
    libOmxAacDec \
    libOmxAlacDec \
    libOmxAmrDec \
    libOmxAmrwbplusDec \
    libOmxApeDec \
    libOmxEvrcDec \
    libOmxG711Dec \
    libOmxQcelp13Dec \
    libOmxVpp \
    libOmxWmaDec \
    libOpenCL \
    libQSEEComAPI \
    libQTEEConnector_listener \
    libQTEEConnector_vendor \
    libSecureUILib \
    libStDrvInt \
    libVkLayer_q3dtools \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libadiertac \
    libadreno_app_profiles \
    libadreno_utils \
    libadsp_default_listener \
    libadsprpc \
    libaise_core \
    libaudcal \
    libaudio_log_utils \
    libaudioalsa \
    libaudioconfigstore \
    libaudioparsers \
    libbase64 \
    libbluetooth_audio_session_qti \
    libbluetooth_audio_session_qti_2_1 \
    libbt-hidlclient \
    libbtnv \
    libc2d30_bltlib \
    libcacertclient \
    libcdsp_default_listener \
    libcdsprpc \
    libcne \
    libcneapiclient \
    libcneoplookup \
    libcneqmiutils \
    libconfigdb \
    libcpion \
    libcvp2 \
    libcvp2_hfi \
    libcvp_common \
    libcvpcpuRev_skel \
    libdiag \
    libdisp-aba \
    libdisplayqos \
    libdisplayskuutils \
    libdpps \
    libdrmfs \
    libdrmtime \
    libdsi_netctrl \
    libdsutils \
    libfastcvdsp_stub \
    libfastcvopt \
    libgcs-calwrapper \
    libgcs-ipc \
    libgcs-osal \
    libgcs \
    libgpudataproducer \
    libgsl \
    libhdcp1prov \
    libhdcp2p2prov \
    libhdcpsrm \
    libhdmipassthru \
    libhta_hexagon_runtime \
    libidl \
    libjnihelper \
    liblistensoundmodel2 \
    libllvm-glnext \
    libllvm-qcom \
    liblqe \
    libmdmdetect \
    libmdsprpc \
    libminkdescriptor \
    libminksocket \
    libmmosal_vendor \
    libmulawdec \
    libnetmgr \
    libnetmgr_common \
    libnetmgr_nr_fusion \
    libnetmgr_rmnet_ext \
    libnlnetmgr \
    libnpu \
    liboemaids_vendor \
    liboemcrypto \
    libopenvx \
    libops \
    libpatchcodeid_vendor \
    libpdmapper \
    libpdnotifier \
    libperipheral_client \
    libqcbor \
    libqcci_legacy \
    libqcmaputils \
    libqcodec2_base \
    libqcodec2_basecodec \
    libqcodec2_core \
    libqcodec2_platform \
    libqcodec2_utils \
    libqcodec2_v4l2codec \
    libqcrilFramework \
    libqcrildatactl \
    libqdi \
    libqdp \
    libqisl \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_csvt_srvc \
    libqmi_encdec \
    libqmi_legacy \
    libqmiservices \
    libqrtr \
    libqsap_sdk \
    libqseed3 \
    libqsocket \
    libqtigef \
    librcc \
    libril-qc-logger \
    libril-qc-ltedirectdisc \
    libril-qc-qmi-1 \
    libril-qc-radioconfig \
    libril-qcril-hook-oem \
    librilqmiservices \
    librmp \
    librpmb \
    libscveCommon \
    libscveCommon_stub \
    libscveObjectSegmentation \
    libscveObjectSegmentation_stub \
    libscveObjectTracker \
    libscveObjectTracker_stub \
    libsdm-color \
    libsdm-colormgr-algo \
    libsdm-diag \
    libsdm-disp-vndapis \
    libsdmextension \
    libsdsprpc \
    libsecureui \
    libsecureui_svcsock \
    libsensorcal \
    libsensorslog \
    libsettings \
    libsns_fastRPC_util \
    libsnsapi \
    libsnsdiaglog \
    libsoc_helper \
    libspl \
    libssc \
    libssc_default_listener \
    libssd \
    libssrec \
    libsysmon_cdsp_skel \
    libsystem_health_mon \
    libthermalclient \
    libtime_genoff \
    libtinyxml2_1 \
    libtrustedapploader \
    libtzdrmgenprov \
    libvendor_rescontrol \
    libvppclient \
    libvpphcp \
    libvpphvx \
    libvpplibrary \
    libvss_common_idl \
    libvss_common_iface \
    libvss_dmi_qcci \
    libvss_gnss_qcci \
    libvss_ims_qcci \
    libvss_nv_idl \
    libvss_nv_iface \
    libvss_resim_core \
    libvss_resim_idl \
    libvss_resim_iface \
    libvssims-impl \
    libwebrtc_audio_preprocessing \
    libwms \
    libwqe \
    libxml \
    qcrild_librilutils \
    qtimutex \
    libaisound \
    libasphere \
    liblgeffectwrapper \
    libqcbassboost \
    libqcreverb \
    libqcvirt \
    libshoebox \
    vendor.display.color@1.0 \
    vendor.display.color@1.1 \
    vendor.display.color@1.2 \
    vendor.display.color@1.3 \
    vendor.display.color@1.4 \
    vendor.display.color@1.5 \
    vendor.display.postproc@1.0 \
    vendor.lge.hardware.powerhint.rescontrol@2.0-common \
    vendor.lge.hardware.powerhint.rescontrol@2.0 \
    vendor.lge.hardware.vss_ims@1.0 \
    vendor.qti.data.factory@2.0 \
    vendor.qti.data.factory@2.1 \
    vendor.qti.data.factory@2.2 \
    vendor.qti.data.factory@2.3 \
    vendor.qti.data.mwqem@1.0 \
    vendor.qti.data.slm@1.0 \
    vendor.qti.hardware.alarm@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.1 \
    vendor.qti.hardware.cacert@1.0 \
    vendor.qti.hardware.data.cne.internal.api@1.0 \
    vendor.qti.hardware.data.cne.internal.constants@1.0 \
    vendor.qti.hardware.data.cne.internal.server@1.0 \
    vendor.qti.hardware.data.connection@1.0 \
    vendor.qti.hardware.data.connection@1.1 \
    vendor.qti.hardware.data.dynamicdds@1.0 \
    vendor.qti.hardware.data.latency@1.0 \
    vendor.qti.hardware.data.lce@1.0 \
    vendor.qti.hardware.data.qmi@1.0 \
    vendor.qti.hardware.dsp@1.0 \
    vendor.qti.hardware.fm@1.0_vendor \
    vendor.qti.hardware.mwqemadapter@1.0 \
    vendor.qti.hardware.qseecom@1.0 \
    vendor.qti.hardware.qteeconnector@1.0_vendor \
    vendor.qti.hardware.radio.am@1.0 \
    vendor.qti.hardware.radio.atcmdfwd@1.0 \
    vendor.qti.hardware.radio.ims@1.0 \
    vendor.qti.hardware.radio.ims@1.1 \
    vendor.qti.hardware.radio.ims@1.2 \
    vendor.qti.hardware.radio.ims@1.3 \
    vendor.qti.hardware.radio.ims@1.4 \
    vendor.qti.hardware.radio.ims@1.5 \
    vendor.qti.hardware.radio.ims@1.6 \
    vendor.qti.hardware.radio.ims@1.7 \
    vendor.qti.hardware.radio.internal.deviceinfo@1.0 \
    vendor.qti.hardware.radio.lpa@1.0 \
    vendor.qti.hardware.radio.lpa@1.1 \
    vendor.qti.hardware.radio.lpa@1.2 \
    vendor.qti.hardware.radio.qcrilhook@1.0 \
    vendor.qti.hardware.radio.qtiradio@1.0 \
    vendor.qti.hardware.radio.qtiradio@2.0 \
    vendor.qti.hardware.radio.qtiradio@2.1 \
    vendor.qti.hardware.radio.qtiradio@2.2 \
    vendor.qti.hardware.radio.qtiradio@2.3 \
    vendor.qti.hardware.radio.qtiradio@2.4 \
    vendor.qti.hardware.radio.qtiradio@2.5 \
    vendor.qti.hardware.radio.qtiradio@2.6 \
    vendor.qti.hardware.radio.uim@1.0 \
    vendor.qti.hardware.radio.uim@1.1 \
    vendor.qti.hardware.radio.uim@1.2 \
    vendor.qti.hardware.radio.uim_remote_client@1.0 \
    vendor.qti.hardware.radio.uim_remote_client@1.1 \
    vendor.qti.hardware.radio.uim_remote_client@1.2 \
    vendor.qti.hardware.radio.uim_remote_server@1.0 \
    vendor.qti.hardware.sensorscalibrate@1.0 \
    vendor.qti.hardware.slmadapter@1.0 \
    vendor.qti.hardware.tui_comm@1.0 \
    vendor.qti.hardware.vpp@1.1 \
    vendor.qti.hardware.vpp@1.2 \
    vendor.qti.hardware.vpp@1.3 \
    vendor.qti.ims.callcapability@1.0 \
    vendor.qti.ims.callinfo@1.0 \
    vendor.qti.ims.factory@1.0 \
    vendor.qti.ims.factory@1.1 \
    vendor.qti.ims.rcsconfig@1.0 \
    vendor.qti.ims.rcsconfig@1.1 \
    vendor.qti.ims.rcsconfig@2.0 \
    vendor.qti.ims.rcsconfig@2.1 \
    vendor.qti.imsrtpservice@3.0-service-Impl \
    vendor.qti.imsrtpservice@3.0_vendor \
    vendor.qti.latency@2.0 \
    vendor.qti.latency@2.1 \
    vendor.qti.memory.pasrmanager@1.0 \
    vendor.qti.memory.pasrmanager@1.1 \
    vendor.qti.power.pasrmanager@1.0 \
    vendor.qti.qspmhal@1.0-impl \
    vendor.qti.qspmhal@1.0_vendor \
    vendor.qti.voiceprint@1.0 \
    com.qualcomm.qti.bluetooth_audio@1.0 \
    libFileMux_proprietary \
    libOmxDsdDec \
    libOmxVideoDSMode \
    libadm \
    libadpcmdec \
    libdrc \
    libdsd2pcm \
    libfastcrc \
    libmm-hdcpmgr \
    libmmrtpdecoder_proprietary \
    libmmrtpencoder_proprietary \
    libpn557_fw \
    libsmwrapper \
    libsurround_3mic_proc \
    libwfdcodecv4l2_proprietary \
    libwfdcommonutils_proprietary \
    libwfdconfigutils_proprietary \
    libwfddisplayconfig_proprietary \
    libwfdhdcpcp \
    libwfdhdcpservice_proprietary \
    libwfdmminterface_proprietary \
    libwfdmmservice_proprietary \
    libwfdmmsrc_proprietary \
    libwfdmodulehdcpsession \
    libwfdrtsp_proprietary \
    libwfdsessionmodule \
    libwfdsourcesession_proprietary \
    libwfdsourcesm_proprietary \
    libwfduibcinterface_proprietary \
    libwfduibcsink_proprietary \
    libwfduibcsinkinterface_proprietary \
    libwfduibcsrc_proprietary \
    libwfduibcsrcinterface_proprietary \
    libwfdutils_proprietary \
    vendor.qti.hardware.wifidisplaysession@1.0_vendor \
    vendor.qti.hardware.wifidisplaysessionl@1.0-halimpl \
    com.qualcomm.qti.dpm.api@1.0_vendor \
    deviceInfoServiceModule \
    android.hardware.gatekeeper@1.0-impl-qti \
    android.hardware.gnss@2.1-impl-qti \
    fingerprint.kona \
    vendor.qti.esepowermanager@1.1-impl \
    vendor.qti.gnss@4.0-impl \
    vendor.qti.hardware.soter@1.0-impl \
    libRbsFlow \
    libaoa \
    libasn1cper \
    libasn1crt \
    libasn1crtx \
    libbatching \
    libcdfw \
    libcdfw_remote_api \
    libdataitems \
    libdpmqmihal \
    libembmsservice \
    libets_teeclient_v2 \
    libfpsph \
    libgdtap \
    libgeofencing \
    libgnss \
    libgnsspps \
    libgps.utils \
    libhdr_tm \
    libhexagon_nn_stub \
    libizat_client_api \
    libizat_core \
    libkeymasterdeviceutils \
    libkeymasterprovision \
    libkeymasterutils \
    liblbs_core \
    libloc_api_v02 \
    libloc_core \
    libloc_socket \
    liblocation_api \
    liblocationservice \
    liblocationservice_glue \
    liblowi_client \
    liblowi_wifihal \
    libmdmimgload \
    libpn557_fw_64 \
    libqcc_file_agent \
    libqmiextservices \
    libqtikeymaster4 \
    libril-qc-hal-qmi \
    libsi \
    libspcom \
    libuicc_vendor \
    libwvhidl \
    libxtadapter \
    libxtwifi_server_protocol \
    libxtwifi_server_protocol_uri_v3 \
    qtibus \
    unnhal-acc-adreno \
    unnhal-acc-common \
    unnhal-acc-hvx \
    vendor.lge.hardware.lgdata@1.0 \
    vendor.lge.hardware.lgdata@1.1 \
    vendor.qti.esepowermanager@1.0 \
    vendor.qti.esepowermanager@1.1 \
    vendor.qti.gnss@1.0 \
    vendor.qti.gnss@1.1 \
    vendor.qti.gnss@1.2 \
    vendor.qti.gnss@2.0 \
    vendor.qti.gnss@2.1 \
    vendor.qti.gnss@3.0 \
    vendor.qti.gnss@4.0-service \
    vendor.qti.gnss@4.0 \
    vendor.qti.hardware.data.iwlan@1.0 \
    vendor.qti.hardware.embmssl@1.0 \
    vendor.qti.hardware.embmssl@1.1 \
    vendor.qti.hardware.factory@1.0 \
    vendor.qti.hardware.factory@1.1 \
    vendor.qti.hardware.qccsyshal@1.0 \
    vendor.qti.hardware.soter@1.0 \
    AlacDecoderModule.so \
    ApeDecoderModule.so \
    AudioContextDetection.so \
    AudioSphereModule.so \
    CFCMModule.so \
    EtsiAmrWbPlusDecModule.so \
    EtsiEaacPlusEncAndCmnModule.so \
    FlacDecoderModule.so \
    HeaacDecoderModule.so \
    LdacModule.so \
    MIC2AMBModule.so \
    SAPlusCmnModule.so \
    SVACmnModule.so \
    VoiceWakeup_V2_Module.so \
    VorbisDecoderModule.so \
    WmaProDecoderModule.so \
    WmaStdDecoderModule.so \
    capi_v2_aptX_CLHDADV_Encoder \
    capi_v2_aptX_CLHDAD_Speech_Decoder \
    fastrpc_shell_0 \
    ffns_module_fv9.so \
    ffv_module_fv9.so \
    fluence_bs_module_fv9.so \
    fluence_ef_module_fv9.so \
    fluence_pro_vc_module_fv9.so \
    fluence_pro_vr_module_fv9.so \
    fluence_sm_module_fv9.so \
    fluence_voiceplus_module.so \
    libQ6MSFR_manager_skel \
    libapps_mem_heap \
    libarcsoft_dualcam_refocus_skel \
    libbitml_nsp_skel \
    libcamera_nn_skel \
    libcvpdsp_skel \
    libdspCV_skel \
    libdsp_streamer_binning \
    libfastcvadsp \
    libfastcvdsp_skel \
    libhalide_hexagon_remote_skel \
    libhexagon_nn_skel \
    libscveObjectSegmentation_skel \
    libscveT2T_skel \
    libsns_device_mode_skel \
    libsns_low_lat_stream_skel \
    libstabilitydomain_skel \
    libsysmon_skel \
    libsysmondomain_skel \
    libsysmonquery_skel \
    mm_fluence_sb_module.so \
    mmecns_module.so \
    sm_fluence_sb_module.so \
    smecns_v2_module_fv9.so \
    com.qualcomm.qti.ant@1.0 \
    com.qualcomm.qti.dpm.api@1.0 \
    fm_helium \
    libQTEEConnector_system \
    libdiag_system \
    libdpmctmgr \
    libdpmfdmgr \
    libdpmframework \
    libdpmtcm \
    libfm-hci \
    libmmosal \
    libmmparser_lite \
    libmmrtpdecoder \
    libmmrtpencoder \
    libseccam-ipc \
    libseccam \
    libwfdclient \
    libwfdcommonutils \
    libwfdconfigutils \
    libwfddisplayconfig \
    libwfdmminterface \
    libwfdmmsink \
    libwfdrtsp \
    libwfdsinksm \
    libwfduibcinterface \
    libwfduibcsink \
    libwfduibcsinkinterface \
    libwfduibcsrc \
    libwfduibcsrcinterface \
    vendor.qti.diaghal@1.0 \
    vendor.qti.hardware.fm@1.0 \
    vendor.qti.hardware.qteeconnector@1.0 \
    vendor.qti.hardware.seccam@1.0 \
    vendor.qti.qspmhal@1.0 \
    com.qualcomm.qti.wifidisplayhal@1.0 \
    libwfdavenhancements \
    libwfdmmsrc_system \
    libwfdservice \
    vendor.qti.hardware.wifidisplaysession@1.0 \
    libaptXHD_encoder \
    libaptX_encoder \
    libimscamera_jni \
    libimsmedia_jni \
    libwfdnative \
    vendor.qti.imsrtpservice@3.0 \
    CneApp \
    IWlanService \
    TimeService \
    pasrservice \
    HotwordEnrollmentOKGoogleHEXAGON \
    HotwordEnrollmentXGoogleHEXAGON \
    QtiTelephonyService \
    WfdService \
    qcrilmsgtunnel \
    seccamservice \
    WfdCommon \
    tcmclient \
    audiosphere \
    com.android.hotwordenrollment.common.util \
    com.qti.dpmframework \
    dpmapi \
    qcrilhook \
    qti-telephony-common \
    android.hardware.gnss@2.1-service-qti.xml \
    android.hardware.neuralnetworks@1.3-service-qti.xml \
    manifest_android.hardware.drm@1.3-service.widevine.xml \
    vendor.qti.gnss@4.0-service.xml \
    ATFWD-daemon \
    adpl \
    adsprpcd \
    cdsprpcd \
    cnd \
    cnss-daemon \
    cpfirmware \
    dpmQmiMgr \
    dspservice \
    fm_qsoc_patches \
    hvdcp_opti \
    android.hardware.bluetooth@1.0-service-qti \
    android.hardware.drm@1.3-service.widevine \
    android.hardware.gatekeeper@1.0-service-qti \
    android.hardware.gnss@2.1-service-qti \
    android.hardware.keymaster@4.0-service-qti \
    android.hardware.neuralnetworks@1.3-service-qti \
    qcrild \
    vendor.display.color@1.0-service \
    vendor.lge.hardware.lgdata@1.1-service \
    vendor.lge.hardware.powerhint.rescontrol@2.0-service \
    vendor.lge.hardware.vss_ims@1.0-service \
    vendor.qti.esepowermanager@1.1-service \
    vendor.qti.hardware.alarm@1.0-service \
    vendor.qti.hardware.capabilityconfigstore@1.0-service \
    vendor.qti.hardware.factory@1.0-service \
    vendor.qti.hardware.qseecom@1.0-service \
    vendor.qti.hardware.qteeconnector@1.0-service \
    vendor.qti.hardware.sensorscalibrate@1.0-service \
    vendor.qti.hardware.soter@1.0-service \
    vendor.qti.hardware.tui_comm@1.0-service-qti \
    vendor.qti.media.c2@1.0-service \
    vendor.qti.power.pasrmanager@1.0-service \
    ims_rtp_daemon \
    imsdatadaemon \
    imsqmidaemon \
    imsrcsd \
    irsc_util \
    ks \
    loc_launcher \
    lowi-server \
    mdm_helper \
    mlid \
    msm_irqbalance \
    netmgrd \
    pd-mapper \
    pm-proxy \
    pm-service \
    power_off_alarm \
    ppd \
    qdcmss \
    qmipriod \
    qni \
    qrtr-cfg \
    qrtr-lookup \
    qrtr-ns \
    qseecomd \
    qti \
    rmt_storage \
    sensors.qti \
    shsusrd \
    sscrpcd \
    ssgqmigd \
    ssgtzd \
    tftp_server \
    thermal-engine \
    time_daemon \
    vendor.qti.qspmhal@1.0-service \
    vppservice \
    wfdhdcphalservice \
    wfdvndservice \
    wifidisplayhalservice \
    xtra-daemon \
    xtwifi-client \
    xtwifi-inet-agent \
    dpmd \
    wfdservice

PRODUCT_PACKAGES += \
    system_ext_priv-app_WfdService_lib_arm64_libwfdnative_so \
    vendor_lib_libEGL_adreno_so \
    vendor_lib_libGLESv2_adreno_so \
    vendor_lib_libq3dtools_adreno_so \
    vendor_lib64_libEGL_adreno_so \
    vendor_lib64_libGLESv2_adreno_so \
    vendor_lib64_libq3dtools_adreno_so

PRODUCT_BOOT_JARS += \
    WfdCommon
